name: Auto-assign Issues

on:
  issues:
    types: [labeled]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: cd packages/auto-assign-issues && npm install

      - name: Auto-assign issue
        run: node packages/auto-assign-issues/src/index.js
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
