name: CI

on:
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.filter }}-${{ matrix.node_version }}-test
      cancel-in-progress: true

    name: ${{ format('Tests ({0})', matrix.description) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            description: macOS
            node_version: 20.19.1
            filter: "--filter=@vite-plugin-cloudflare/playground"
          # needs to run on the amd runners to allow containers test to work in CI
          - os: ubuntu-24.04
            description: Linux
            node_version: 20.19.1
            # ./tools _only_ runs here because they're only intended to run in CI
            # Browser rendering is disabled here because of https://pptr.dev/troubleshooting#issues-with-apparmor-on-ubuntu
            filter: "--filter=@vite-plugin-cloudflare/playground"
          - os: windows-latest
            description: Windows
            node_version: 20.19.1
            filter: "--filter=@vite-plugin-cloudflare/playground"
          # needs to run on the amd runners to allow containers test to work in CI
          - os: ubuntu-24.04
            description: v22, Linux
            node_version: 22
            # Browser rendering is disabled here because of https://pptr.dev/troubleshooting#issues-with-apparmor-on-ubuntu
            filter: "--filter=@vite-plugin-cloudflare/playground"
          # Skipped until we upgrade to undici v7, because of https://github.com/nodejs/undici/issues/4285
          # - os: ubuntu-24.04-arm
          #   label: v24, Linux
          #   node_version: 24
          #   filter: '--filter=@vite-plugin-cloudflare/playground'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            everything_but_markdown:
              - '!**/*.md'

      - name: Install Dependencies
        if: steps.changes.outputs.everything_but_markdown == 'true'
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
          node-version: ${{ matrix.node_version }}

      - name: Bump package versions
        if: steps.changes.outputs.everything_but_markdown == 'true'
        run: node .github/changeset-version.js
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check for Wrangler build cache
        if: steps.changes.outputs.everything_but_markdown == 'true'
        run: pnpm build -F wrangler --dry-run
        env:
          TEST_CLOUDFLARE_API_TOKEN: ${{ secrets.TEST_CLOUDFLARE_API_TOKEN }}
          TEST_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.TEST_CLOUDFLARE_ACCOUNT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192"
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
          TEST_REPORT_PATH: ${{ runner.temp }}/test-report/index.html
          CI_OS: ${{ matrix.description }}

      - name: Run tests
        if: steps.changes.outputs.everything_but_markdown == 'true'
        run: pnpm run test:ci --concurrency 1 ${{ matrix.filter }} --log-order=stream
        env:
          TEST_CLOUDFLARE_API_TOKEN: ${{ secrets.TEST_CLOUDFLARE_API_TOKEN }}
          TEST_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.TEST_CLOUDFLARE_ACCOUNT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192"
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
          TEST_REPORT_PATH: ${{ runner.temp }}/test-report/index.html
          CI_OS: ${{ matrix.description }}

      - name: Upload turbo logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: turbo-runs-${{ matrix.os }}-${{ matrix.node }}
          path: .turbo/runs
